name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --ignore=E501 --show-source --statistics

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Railway
      run: npm i -g @railway/cli
      
    - name: Run Docker container locally
      run: |
      docker run -d --name my_container -p 8000:8000 registry.railway.app/${{ secrets.RAILWAY_PROJECT_NAME }}/fastapi:latest
      sleep 10
      curl -f http://localhost:8000 || exit 1
      docker stop my_container
      docker rm my_container

    - name: Deploy
      working-directory: movie_recommendation_system
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
